gsr_admin_page_management:
  username_input:   # 姓名输入框
    by: "id"
    value: "username"
  password_input:   # 密码输入框
    by: "id"
    value: "password"
  code_input:   # 验证码输入框
    by: "id"
    value: "code"
  login_button:   # 登录按钮
    by: "xpath"
    value: "//*[@id='root-master']/div/div/div/div[2]/form/button"
  user_part: # 用户中心（右上角）
    by: "xpath"
    value:  "//div[@id='root']/div/div/div[2]/header[2]/div/div[3]/div/div/div/div[@class='ant-space-item'][2]"
  management_button:  # 管理菜单按钮
    by: "xpath"
    value: "//*[@id='root-master']/div/div/div/div/ul/li[1]"
  payroll_list:  # payroll主菜单
    by: "xpath"
    value: "//a[@title='Payroll']"
  ettlement_list:  # 结算管理（新）主菜单
    by: "xpath"
    value:  "//a[@title='结算管理（新）']"
  payment_settlement:  # 收款结算
    by: "xpath"
    value: "//a[@title='收款结算']"
  eor_settlement:  # EOR类收款
    by: "xpath"
    value: "//a[@title='EOR类收款']"
  create_salary_package:  # 创建薪资包
    by: "xpath"
    value: "//button[text()='薪资包']"
  client_input:  # 客户选择框
    by: "xpath"
    value: "//input[@id='clientId']"
  client_text:  # 客户输入验证
    by: "xpath"
    value: "//div[contains(@class,'ant-form-item') and .//label[@for='clientId']]//span[contains(@class,'ant-select-selection-item')]"
  client_contract_input:  # 客户合同选择框
    by: "xpath"
    value: "//input[@id='clientContractId']"
  client_contract_text:  # 客户合同验证框
    by: "xpath"
    value: "//div[contains(@class,'ant-form-item') and .//label[@for='clientContractId']]//span[contains(@class,'ant-select-selection-item')]"
  country_input: # 国家/地区选择框
    by: "xpath"
    value: "//div[contains(@class,'ant-modal')]//input[@id='country']"
  country_text:  # 国家/地区验证框
    by: "xpath"
    value: "//div[contains(@class,'ant-form-item') and .//label[@for='country']]//span[contains(@class,'ant-select-selection-item')]"
  service_month_input:  # 服务月份选择框
    by: "xpath"
    value: "//div[contains(@class,'ant-modal')]//input[@id='servicesTime']"
  onboarding_country_input:  # 就职国家选择框
    by: "xpath"
    value: "//div[contains(@class,'ant-modal')]//input[@id='onboardingCountry']"
  onboarding_country_text:  # 就职国家验证框
    by: "xpath"
    value: "//div[contains(@class,'ant-form-item') and .//label[@for='onboardingCountry']]//span[contains(@class,'ant-select-selection-item')]"
  consultan_flag:  # 员工性质选择框
    by: "xpath"
    value: "//div[contains(@class,'ant-modal')]//input[@id='consultantFlag']"
  consultanflag_text:  # 员工性质校验框
    by: "xpath"
    value: "//div[contains(@class,'ant-form-item') and .//label[@for='consultantFlag']]//span[contains(@class,'ant-select-selection-item')]"
  confirm_button:  # 创建EOR薪资包弹窗-确认按钮
    by : "xpath"
    value: "//div[contains(@class,'ant-modal-footer')]//button[contains(@class,'ant-btn-primary')]"
  settlement_package_code:  # EOR薪资包code-提取用
    by: "xpath"
    value: "//div[contains(@class,'ant-form-item') and .//label[@for='settlementPackageCode']]//div[contains(@class,'ant-form-item-control-input-content')]"
  create_employee_settlement:  # 创建员工结算单
    by: "xpath"
    value: "//div[contains(@class,'ant-pro-table')]//button[normalize-space()='创建员工结算单']"
  employee_input:  # 员工姓名选择框
    by: "xpath"
    value: "//div[@class='bill-modal-content']//input[@id='externalEmployeeId']"
  employee_text:  # 员工姓名校验框
    by: "xpath"
    value: "//div[@class='bill-modal-content']//span[contains(@class,'ant-select-selection-item')]"
  staffid_value:  # 员工staffid-提取，用于后续校验
    by: "xpath"
    value: "//div[@class='bill-modal-content']//input[@id='staffId']"
  confirm_employee_settlement:  # 确认员工结算单
    by: "xpath"
    value: "//div[contains(@class,'ant-modal') and .//div[@class='bill-modal-content']]//div[contains(@class,'ant-modal-footer')]//button[contains(@class,'ant-btn-primary')]"
  employee_settlement_staffid:  # 员工结算单staffid
    by: "xpath"
    value: "//div[@class='ant-spin-container']//div[@class='ant-table-container']//tbody//tr[2]//td[5]"
